create schema "Users";
create sequence "Users"."Locations_ID_seq" start with 1 increment by 1 minvalue 1 maxvalue 2147483647 no cycle cache 1;
create sequence "Users"."Sessions_ID_seq" start with 1 increment by 1 minvalue 1 maxvalue 2147483647 no cycle cache 1;
create sequence "Users"."Users_ID_seq" start with 1 increment by 1 minvalue 1 maxvalue 2147483647 no cycle cache 1;
create table "User" (
                        "ID" int not null default next value for "Users"."Users_ID_seq",
                        "Login" varchar(40) not null,
                        "Password" varchar(40) not null,
                        "Name" varchar(40) not null,
                        constraint "Users_pkey" primary key ("ID"),
                        constraint users_un unique ("Login")
);
create table "Locations" (
                             "ID" int not null generated by default as identity,
                             "Name" char not null,
                             "UserID" int not null default 0,
                             "Latitude" numeric not null,
                             "Longtitude" numeric not null,
                             constraint "Locations_pkey" primary key ("ID"),
                             constraint "UsertAddFK" foreign key ("UserID") references "User" ("ID") on delete set default on update cascade
);
create table "Sessions" (
                            "ID" int not null generated by default as identity,
                            "UserID" int not null,
                            "ExpiresAt" timestamp not null,
                            constraint "Sessions_pkey" primary key ("ID"),
                            constraint "SessinoID_FK" foreign key ("UserID") references "User" ("ID") on delete cascade on update cascade
);